services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - postgres_optimization:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 6

volumes:
  postgres_optimization:
